# Generated by Django 6.0.5 on 2026-05-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='itemimage',
            table='listing_images',
        ),
        migrations.AlterModelTable(
            name='listing',
            table='listings',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
