# Generated by Django 6.0.5 on 2026-06-01 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_user_options_alter_itemimage_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SCAM', 'Prohibited/Scam Content'), ('INAPPROPRIATE', 'Inappropriate Language/Media'), ('MISCATEGORIZED', 'Incorrect Category'), ('DUPLICATE', 'Duplicate Listing'), ('OTHER', 'Other Issues')], help_text='The specific violation category.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional context provided by the reporter.', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Track whether the admin has reviewed and actioned this report.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='The listing being reported.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.listing')),
                ('reporter', models.ForeignKey(help_text='The user who filed the report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
