# Generated by Django 6.0.5 on 2026-06-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='listing',
            field=models.ForeignKey(blank=True, help_text='The listing being reported (Optional for system bugs).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.listing'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('SCAM', 'Prohibited/Scam Content'), ('INAPPROPRIATE', 'Inappropriate Language/Media'), ('MISCATEGORIZED', 'Incorrect Category'), ('DUPLICATE', 'Duplicate Listing'), ('SYSTEM_BUG', 'System Flaw/Bug Report'), ('OTHER', 'Other Issues')], help_text='The specific violation category.', max_length=20),
        ),
    ]
