# Generated by Django 6.0.5 on 2026-06-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User identity image for the marketplace.', null=True, upload_to='profiles/'),
        ),
    ]
